DECLARE
A NUMBER :=&A;
B NUMBER :=&B;
C NUMBER :=&C;
BEGIN 
IF A>B AND A>C THEN
DBMS_OUTPUT.PUT_LINE(A||' IS BIGGEST');
ELSIF B>A AND B>C THEN
DBMS_OUTPUT.PUT_LINE(B||' IS BIGGEST');
ELSE
DBMS_OUTPUT.PUT_LINE(C||' IS BIGGEST');
END IF;
END;

